(async function(){
 const data=await loadJSON('data/tutorials.json'); const software=await loadJSON('data/software.json');
 const list=document.getElementById('tutorial-list'), q=document.getElementById('tutorial-search'), sf=document.getElementById('tutorial-software'), df=document.getElementById('tutorial-difficulty');
 software.forEach(x=>sf.insertAdjacentHTML('beforeend',`<option value="${x.id}">${escapeHtml(x.name)}</option>`));
 function card(x){return `<a class="article-card" href="tutorials.html?slug=${encodeURIComponent(x.slug)}"><div class="topline"><span class="difficulty">${escapeHtml(x.difficulty)}</span><span class="tag">${escapeHtml(x.time)}</span></div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description)}</p><div class="card-meta"><span class="tag">${escapeHtml(software.find(s=>s.id===x.software)?.name||x.software)}</span></div></a>`}
 function render(){const query=(q.value||'').toLowerCase(),out=data.filter(x=>(!query||(x.title+' '+x.description).toLowerCase().includes(query))&&(!sf.value||x.software===sf.value)&&(!df.value||x.difficulty===df.value));list.innerHTML=out.map(card).join('')||'<div class="empty">No tutorials found.</div>'}
 [q,sf,df].forEach(e=>e.addEventListener('input',render)); render();
 const slug=new URLSearchParams(location.search).get('slug');
 if(slug){const x=data.find(v=>v.slug===slug);if(x) detail(x)}
 function detail(x){const s=software.find(v=>v.id===x.software);document.title=x.title+' | Enterprise AI Software Assistant';document.querySelector('main').innerHTML=`<section class="page-hero"><div class="container"><div class="eyebrow">${escapeHtml(x.difficulty)} • ${escapeHtml(x.time)}</div><h1>${escapeHtml(x.title)}</h1><p>${escapeHtml(x.description)}</p></div></section><section class="section"><div class="container prose"><p><strong>Software:</strong> ${escapeHtml(s?.name||x.software)}</p><h2>Overview</h2><p>${escapeHtml(x.description)}</p><h2>Prerequisites</h2><ul>${x.prerequisites.map(v=>`<li>${escapeHtml(v)}</li>`).join('')}</ul><h2>Required Permissions</h2><p>${escapeHtml(x.permissions)}</p><h2>Step-by-Step Instructions</h2><ol>${x.steps.map(v=>`<li>${escapeHtml(v)}</li>`).join('')}</ol><h2>Expected Result</h2><p>${escapeHtml(x.result)}</p><h2>Troubleshooting</h2><p>${escapeHtml(x.troubleshooting)}</p><h2>Common Mistakes</h2><ul>${x.mistakes.map(v=>`<li>${escapeHtml(v)}</li>`).join('')}</ul><div class="article-card"><h2>Was this tutorial helpful?</h2><button class="btn btn-ghost" onclick="this.textContent='Thanks for the feedback!'">👍 Yes</button> <button class="btn btn-ghost" onclick="this.textContent='Feedback received'">👎 No</button></div></div></section>`}
})();
